import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import AuthProvider from './api/auth/Provider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="no-js">
      <head>
     {/* <meta charset="utf-8"/>  */}
        <meta http-equiv="x-ua-compatible" content="ie=edge" />
        <title> Bizzar - NextJS &amp; Greivin Cruz </title>
        <meta name="description" content="" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        {/* <!-- Place favicon.ico in the root directory --> */}
        <link
          rel="shortcut icon"
          type="image/x-icon"
          href="assets/img/logo/favicon.png"
        />
        {/* <!-- ========== Start Stylesheet ========== --> */}
        <link href="assets/css/bootstrap.min.css" rel="stylesheet" />
        <link href="assets/css/all.min.css" rel="stylesheet" />
        <link href="assets/css/animate.css" rel="stylesheet" />
        <link href="assets/css/themify-icons.css" rel="stylesheet" />
        <link href="assets/css/icofont.min.css" rel="stylesheet" />
        <link href="assets/css/flaticon.css" rel="stylesheet" />
        <link href="assets/css/bootstrap-icons.css" rel="stylesheet" />
        <link href="assets/css/bsnav.min.css" rel="stylesheet" />
        <link href="assets/css/preloader.css" rel="stylesheet" />
        <link href="assets/css/magnific-popup.css" rel="stylesheet" />
        <link href="assets/css/swiper-bundle.min.css" rel="stylesheet" />
        <link href="assets/css/jquery-ui.css" rel="stylesheet" />
        <link href="assets/style.css" rel="stylesheet" />
        <link href="style.css" rel="stylesheet" />
        <link href="assets/css/responsive.css" rel="stylesheet" />
        {/* <!-- ========== End Stylesheet ========== --> */}
      </head>
        <AuthProvider>
      <body id="bdy" className={inter.className}>
        {children}
       
        {/* <!-- Start Scroll top	============================================= --> */}
        <a href="#bdy" id="scrtop" className="smooth-menu">
          <i className="ti-arrow-up"></i>
        </a>
        {/* <!-- End Scroll top--> */}
        {/* 	
	<!-- jQuery Frameworks    ============================================= --> */}
        <script src="assets/js/jquery-3.7.0.min.js" async></script>
        <script src="assets/js/popper.min.js" async></script>
        <script src="assets/js/bootstrap.min.js" async></script>
        <script src="assets/js/bsnav.min.js" async></script>
        <script src="assets/js/jquery.magnific-popup.min.js" async></script>
        <script src="assets/js/isotope.pkgd.min.js" async></script>
        <script src="assets/js/imagesloaded.pkgd.min.js" async></script>
        <script src="assets/js/wow.min.js" async></script>
        <script src="assets/js/count-to.js" async></script>
        <script src="assets/js/progress-bar.min.js" async></script>
        <script src="assets/js/jquery.easypiechart.js" async></script>
        <script src="assets/js/typed.js" async></script>
        <script src="assets/js/YTPlayer.min.js" async></script>
        <script src="assets/js/jquery.appear.js" async></script>
        <script src="assets/js/jquery.easing.min.js" async></script>
        <script src="assets/js/swiper-bundle.min.js" async></script>
        <script src="assets/js/active-class.js" async></script>
        <script src="assets/js/jquery-ui.min.js" async></script>
        <script src="assets/js/main.js" async></script>
      </body>
      </AuthProvider>
    </html>
  );
}
